### PR TITLE
avoid heartbeat/unlock deadlock

### PR DESCRIPTION
**Pull request by toejough**
discovered while testing a package that now depends on this one - sometimes lock release hangs.  Turns out both the lock release and the heartbeat lock the same internal mutex.  This update resolves that race condition.

### CODE REVIEW

**Comment by ucirello** [comment]
@toejough thanks for the PR - could you please add a test proving the bug?

**Comment by toejough** [comment]
I'd love to, but I won't promise it.  I found this in the course of a higher level test running when using this library as a dependency, and pulling that test down into this library has proven to be non-trivial, and my paycheck depends on putting my attention elsewhere at the moment.  That kind of sucks, and I know that, so I'll try to get a test together, but if I'm not fast with a turnaround, I want you to know I'm not just ghosting you!

**Comment by toejough** [comment]
I will try to make time for a test next week!

**Comment by ucirello** [comment]
hi @toejough -- reviewing the code I can see where the problem is. Let's try this one together.

**Comment by ucirello** [comment]
hi @toejough - I managed to isolate the problem with a test. I am replacing this PR with the commit coming in.

**Pull request closed without merging**
