### PR TITLE
Add function to cleanup table

### PR DESCRIPTION
**Pull request by dlm**
Maybe all the testing is a little overkill. :)

### CODE REVIEW

**Comment by ucirello** [comment]
Hi could you please elaborate what's the goal of this PR? Why does this library need the drop call? Why can you not call the drop directly in the DB connection?

**Comment by dlm** [comment]
Adding the function increases encapsulation.  In particular, it removes a leaky abstraction and creates a function at the same level of abstraction as the current library for clean up.

For a little more detail, in my project, I call `CreateTable`, which (as you know) initializes postgres for using this library.  In particular, it creates a table and sequence.  In my code, I directly call `DROP TABLE`, which cascades dropping the sequence.  

This PR improves pglock as follows.  Currently, a user of the library does not need to know the schema required by pglock except for cleanup.  Should the schema change, `CreateTable` will still do what it does, but directly calling `DROP TABLE` may no longer clean up correctly.  A function for cleaning up at the same level of abstraction as `CreateTable` create a place for such code.

**Comment by ucirello** [comment]
OK - I think I see what you are meaning. In any case, there was a loss in test coverage. As soon as you address that I am going to merge this PR.

**Comment by dlm** [comment]
Great!  Your library made my life 1000x easier and I am glad that I could add something!  Please, let me know if there are additional ways that I can help out.

**Comment by dlm** [comment]
I added a test for the failure case.  So coverage is now back to 100%.

Screenshot from 2020-09-22 08-23-09

Please, let me know if there is any additional feedback that you would like me to address.

**Comment by ucirello** [comment]
Manually merged with b76be34db4ac6c36c48eeae55fb915592077cb9f

Thanks @dlm

**Pull request closed without merging**
